//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDesk.Localization.Domain {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketDesk.Localization.Domain.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Allow users to edit priority?.
        /// </summary>
        public static string AllowInternalUsersToEditPriority {
            get {
                return ResourceManager.GetString("AllowInternalUsersToEditPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Allow users to edit tags?.
        /// </summary>
        public static string AllowInternalUsersToEditTags {
            get {
                return ResourceManager.GetString("AllowInternalUsersToEditTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Allow internal users to set the assigned to field (new ticket creation only)?.
        /// </summary>
        public static string AllowInternalUsersToSetAssigned {
            get {
                return ResourceManager.GetString("AllowInternalUsersToSetAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Allow internal users to set or change the ticket owner?.
        /// </summary>
        public static string AllowInternalUsersToSetOwner {
            get {
                return ResourceManager.GetString("AllowInternalUsersToSetOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}: from &quot;{1}&quot; to &quot;{2}&quot;.
        /// </summary>
        public static string Changes_From_To {
            get {
                return ResourceManager.GetString("Changes_From_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Changes:.
        /// </summary>
        public static string Changes_Title {
            get {
                return ResourceManager.GetString("Changes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User is not authorized to perform this activity..
        /// </summary>
        public static string CheckSecurity_NotAuthorized {
            get {
                return ResourceManager.GetString("CheckSecurity_NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a My Assigned.
        /// </summary>
        public static string DefaultListNameAssignedToMe {
            get {
                return ResourceManager.GetString("DefaultListNameAssignedToMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ticket History.
        /// </summary>
        public static string DefaultListNameHistoryTickets {
            get {
                return ResourceManager.GetString("DefaultListNameHistoryTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a My Tickets.
        /// </summary>
        public static string DefaultListNameMyTickets {
            get {
                return ResourceManager.GetString("DefaultListNameMyTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Open Tickets.
        /// </summary>
        public static string DefaultListNameOpenTickets {
            get {
                return ResourceManager.GetString("DefaultListNameOpenTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unassigned.
        /// </summary>
        public static string DefaultListNameUnassigned {
            get {
                return ResourceManager.GetString("DefaultListNameUnassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Default Logon Domain.
        /// </summary>
        public static string DefaultLogonDomain {
            get {
                return ResourceManager.GetString("DefaultLogonDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Default New User Roles.
        /// </summary>
        public static string DefaultNewUserRoles {
            get {
                return ResourceManager.GetString("DefaultNewUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User is not authorized to create new tickets.
        /// </summary>
        public static string ExceptionSecurityUserCannotCreateNewTicket {
            get {
                return ResourceManager.GetString("ExceptionSecurityUserCannotCreateNewTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Setting type conversion error: unable to convert SettingName [{0}] to specified SettingType [{1}].
        /// </summary>
        public static string ExceptionSettingsTypeConversionError {
            get {
                return ResourceManager.GetString("ExceptionSettingsTypeConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Description.
        /// </summary>
        public static string Project_Description {
            get {
                return ResourceManager.GetString("Project_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Project Name.
        /// </summary>
        public static string Project_Name {
            get {
                return ResourceManager.GetString("Project_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Categories.
        /// </summary>
        public static string SelectList_Categories {
            get {
                return ResourceManager.GetString("SelectList_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Priorities.
        /// </summary>
        public static string SelectList_Priorities {
            get {
                return ResourceManager.GetString("SelectList_Priorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ticket Types.
        /// </summary>
        public static string SelectList_TicketTypes {
            get {
                return ResourceManager.GetString("SelectList_TicketTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Assign.
        /// </summary>
        public static string TicketActivity_Assign {
            get {
                return ResourceManager.GetString("TicketActivity_Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel More Info.
        /// </summary>
        public static string TicketActivity_CancelMoreInfo {
            get {
                return ResourceManager.GetString("TicketActivity_CancelMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Close.
        /// </summary>
        public static string TicketActivity_Close {
            get {
                return ResourceManager.GetString("TicketActivity_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Comment.
        /// </summary>
        public static string TicketActivity_Comment {
            get {
                return ResourceManager.GetString("TicketActivity_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create.
        /// </summary>
        public static string TicketActivity_Create {
            get {
                return ResourceManager.GetString("TicketActivity_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create.
        /// </summary>
        public static string TicketActivity_CreateOnBehalfOf {
            get {
                return ResourceManager.GetString("TicketActivity_CreateOnBehalfOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit.
        /// </summary>
        public static string TicketActivity_Edit {
            get {
                return ResourceManager.GetString("TicketActivity_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit Attachments.
        /// </summary>
        public static string TicketActivity_EditAttachments {
            get {
                return ResourceManager.GetString("TicketActivity_EditAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Force Close.
        /// </summary>
        public static string TicketActivity_ForceClose {
            get {
                return ResourceManager.GetString("TicketActivity_ForceClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Give Up.
        /// </summary>
        public static string TicketActivity_GiveUp {
            get {
                return ResourceManager.GetString("TicketActivity_GiveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pass.
        /// </summary>
        public static string TicketActivity_Pass {
            get {
                return ResourceManager.GetString("TicketActivity_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Provide Info.
        /// </summary>
        public static string TicketActivity_ProvideInfo {
            get {
                return ResourceManager.GetString("TicketActivity_ProvideInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Re-assign.
        /// </summary>
        public static string TicketActivity_ReAssign {
            get {
                return ResourceManager.GetString("TicketActivity_ReAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Re-open.
        /// </summary>
        public static string TicketActivity_ReOpen {
            get {
                return ResourceManager.GetString("TicketActivity_ReOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Request More Info.
        /// </summary>
        public static string TicketActivity_RequestMoreInfo {
            get {
                return ResourceManager.GetString("TicketActivity_RequestMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Resolve.
        /// </summary>
        public static string TicketActivity_Resolve {
            get {
                return ResourceManager.GetString("TicketActivity_Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Take Over.
        /// </summary>
        public static string TicketActivity_TakeOver {
            get {
                return ResourceManager.GetString("TicketActivity_TakeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a added comment.
        /// </summary>
        public static string TicketActivityAddComment {
            get {
                return ResourceManager.GetString("TicketActivityAddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a assigned the ticket to {0}.
        /// </summary>
        public static string TicketActivityAssign {
            get {
                return ResourceManager.GetString("TicketActivityAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a has cancelled the request for more information.
        /// </summary>
        public static string TicketActivityCancelMoreInfo {
            get {
                return ResourceManager.GetString("TicketActivityCancelMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a closed the ticket.
        /// </summary>
        public static string TicketActivityClose {
            get {
                return ResourceManager.GetString("TicketActivityClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a created the ticket.
        /// </summary>
        public static string TicketActivityCreate {
            get {
                return ResourceManager.GetString("TicketActivityCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a created the ticket on behalf of {0}.
        /// </summary>
        public static string TicketActivityCreateOnBehalfOf {
            get {
                return ResourceManager.GetString("TicketActivityCreateOnBehalfOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a modified ticket.
        /// </summary>
        public static string TicketActivityEditTicketInfo {
            get {
                return ResourceManager.GetString("TicketActivityEditTicketInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a closed the ticket by force.
        /// </summary>
        public static string TicketActivityForceClose {
            get {
                return ResourceManager.GetString("TicketActivityForceClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a has given up on the ticket.
        /// </summary>
        public static string TicketActivityGiveUp {
            get {
                return ResourceManager.GetString("TicketActivityGiveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a modified ticket attachments.
        /// </summary>
        public static string TicketActivityModifyAttachments {
            get {
                return ResourceManager.GetString("TicketActivityModifyAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a passed the ticket to {0}.
        /// </summary>
        public static string TicketActivityPass {
            get {
                return ResourceManager.GetString("TicketActivityPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  at a priority of {0}.
        /// </summary>
        public static string TicketActivityPriority {
            get {
                return ResourceManager.GetString("TicketActivityPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a and reactivated the ticket..
        /// </summary>
        public static string TicketActivityReactivate {
            get {
                return ResourceManager.GetString("TicketActivityReactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a reassigned the ticket to {0}.
        /// </summary>
        public static string TicketActivityReAssign {
            get {
                return ResourceManager.GetString("TicketActivityReAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a re-opened the ticket.
        /// </summary>
        public static string TicketActivityReOpen {
            get {
                return ResourceManager.GetString("TicketActivityReOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a has requested more information.
        /// </summary>
        public static string TicketActivityRequestMoreInfo {
            get {
                return ResourceManager.GetString("TicketActivityRequestMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a resolved the ticket.
        /// </summary>
        public static string TicketActivityResolve {
            get {
                return ResourceManager.GetString("TicketActivityResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a has provided more information.
        /// </summary>
        public static string TicketActivitySupplyMoreInfo {
            get {
                return ResourceManager.GetString("TicketActivitySupplyMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a has taken over the ticket.
        /// </summary>
        public static string TicketActivityTakeOver {
            get {
                return ResourceManager.GetString("TicketActivityTakeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Actual Duration.
        /// </summary>
        public static string TicketActualDuration {
            get {
                return ResourceManager.GetString("TicketActualDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Actual.
        /// </summary>
        public static string TicketActualDurationShort {
            get {
                return ResourceManager.GetString("TicketActualDurationShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Affects Customer.
        /// </summary>
        public static string TicketAffectsCustomer {
            get {
                return ResourceManager.GetString("TicketAffectsCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Customer.
        /// </summary>
        public static string TicketAffectsCustomerShort {
            get {
                return ResourceManager.GetString("TicketAffectsCustomerShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Assigned To.
        /// </summary>
        public static string TicketAssignedTo {
            get {
                return ResourceManager.GetString("TicketAssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Assigned.
        /// </summary>
        public static string TicketAssignedToShort {
            get {
                return ResourceManager.GetString("TicketAssignedToShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Category.
        /// </summary>
        public static string TicketCategory {
            get {
                return ResourceManager.GetString("TicketCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Category.
        /// </summary>
        public static string TicketCategoryShort {
            get {
                return ResourceManager.GetString("TicketCategoryShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Created By.
        /// </summary>
        public static string TicketCreatedBy {
            get {
                return ResourceManager.GetString("TicketCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Created By.
        /// </summary>
        public static string TicketCreatedByShort {
            get {
                return ResourceManager.GetString("TicketCreatedByShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Created Date.
        /// </summary>
        public static string TicketCreatedDate {
            get {
                return ResourceManager.GetString("TicketCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Created Date.
        /// </summary>
        public static string TicketCreatedDateShort {
            get {
                return ResourceManager.GetString("TicketCreatedDateShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Status Date.
        /// </summary>
        public static string TicketCurrentStatusDate {
            get {
                return ResourceManager.GetString("TicketCurrentStatusDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Status Date.
        /// </summary>
        public static string TicketCurrentStatusDateShort {
            get {
                return ResourceManager.GetString("TicketCurrentStatusDateShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Status By.
        /// </summary>
        public static string TicketCurrentStatusSetBy {
            get {
                return ResourceManager.GetString("TicketCurrentStatusSetBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Status By.
        /// </summary>
        public static string TicketCurrentStatusSetByShort {
            get {
                return ResourceManager.GetString("TicketCurrentStatusSetByShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Details.
        /// </summary>
        public static string TicketDetails {
            get {
                return ResourceManager.GetString("TicketDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Details.
        /// </summary>
        public static string TicketDetailsShort {
            get {
                return ResourceManager.GetString("TicketDetailsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Due Date.
        /// </summary>
        public static string TicketDueDate {
            get {
                return ResourceManager.GetString("TicketDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Due.
        /// </summary>
        public static string TicketDueDateShort {
            get {
                return ResourceManager.GetString("TicketDueDateShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Estimated Duration.
        /// </summary>
        public static string TicketEstimatedDuration {
            get {
                return ResourceManager.GetString("TicketEstimatedDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Estimated.
        /// </summary>
        public static string TicketEstimatedDurationShort {
            get {
                return ResourceManager.GetString("TicketEstimatedDurationShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Is Html.
        /// </summary>
        public static string TicketIsHtml {
            get {
                return ResourceManager.GetString("TicketIsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Is Html.
        /// </summary>
        public static string TicketIsHtmlShort {
            get {
                return ResourceManager.GetString("TicketIsHtmlShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Updated By.
        /// </summary>
        public static string TicketLastUpdateBy {
            get {
                return ResourceManager.GetString("TicketLastUpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Updated By.
        /// </summary>
        public static string TicketLastUpdateByShort {
            get {
                return ResourceManager.GetString("TicketLastUpdateByShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Updated Date.
        /// </summary>
        public static string TicketLastUpdateDate {
            get {
                return ResourceManager.GetString("TicketLastUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Updated Date.
        /// </summary>
        public static string TicketLastUpdateDateShort {
            get {
                return ResourceManager.GetString("TicketLastUpdateDateShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Owner.
        /// </summary>
        public static string TicketOwner {
            get {
                return ResourceManager.GetString("TicketOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Owner.
        /// </summary>
        public static string TicketOwnerShort {
            get {
                return ResourceManager.GetString("TicketOwnerShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Priority.
        /// </summary>
        public static string TicketPriority {
            get {
                return ResourceManager.GetString("TicketPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Priority.
        /// </summary>
        public static string TicketPriorityShort {
            get {
                return ResourceManager.GetString("TicketPriorityShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Project.
        /// </summary>
        public static string TicketProject {
            get {
                return ResourceManager.GetString("TicketProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Project.
        /// </summary>
        public static string TicketProjectShort {
            get {
                return ResourceManager.GetString("TicketProjectShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Resolution Date.
        /// </summary>
        public static string TicketResolutionDate {
            get {
                return ResourceManager.GetString("TicketResolutionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Resolution.
        /// </summary>
        public static string TicketResolutionDateShort {
            get {
                return ResourceManager.GetString("TicketResolutionDateShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Active.
        /// </summary>
        public static string TicketStatusActive {
            get {
                return ResourceManager.GetString("TicketStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Closed.
        /// </summary>
        public static string TicketStatusClosed {
            get {
                return ResourceManager.GetString("TicketStatusClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a More Info.
        /// </summary>
        public static string TicketStatusMoreInfo {
            get {
                return ResourceManager.GetString("TicketStatusMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Resolved.
        /// </summary>
        public static string TicketStatusResolved {
            get {
                return ResourceManager.GetString("TicketStatusResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tags.
        /// </summary>
        public static string TicketTagList {
            get {
                return ResourceManager.GetString("TicketTagList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tags.
        /// </summary>
        public static string TicketTagListShort {
            get {
                return ResourceManager.GetString("TicketTagListShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Target Date.
        /// </summary>
        public static string TicketTargetDate {
            get {
                return ResourceManager.GetString("TicketTargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Target.
        /// </summary>
        public static string TicketTargetDateShort {
            get {
                return ResourceManager.GetString("TicketTargetDateShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ticket Id.
        /// </summary>
        public static string TicketTicketId {
            get {
                return ResourceManager.GetString("TicketTicketId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Id.
        /// </summary>
        public static string TicketTicketIdShort {
            get {
                return ResourceManager.GetString("TicketTicketIdShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Status.
        /// </summary>
        public static string TicketTicketStatus {
            get {
                return ResourceManager.GetString("TicketTicketStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Status.
        /// </summary>
        public static string TicketTicketStatusShort {
            get {
                return ResourceManager.GetString("TicketTicketStatusShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type.
        /// </summary>
        public static string TicketTicketType {
            get {
                return ResourceManager.GetString("TicketTicketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type.
        /// </summary>
        public static string TicketTicketTypeShort {
            get {
                return ResourceManager.GetString("TicketTicketTypeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Title.
        /// </summary>
        public static string TicketTitle {
            get {
                return ResourceManager.GetString("TicketTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Title.
        /// </summary>
        public static string TicketTitleShort {
            get {
                return ResourceManager.GetString("TicketTitleShort", resourceCulture);
            }
        }
    }
}
